config/routes.rb
# frozen_string_literal: true

# routes
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources :users
  mount Sidekiq::Web => '/sidekiq'
  get '/search', to: 'users#search'
  resources :stories
  resources :posts do
    resources :photos, only: [:create]
    resources :likes, only: %i[create destroy], shallow: true
    resources :comments, shallow: true
  end
end

app/models/user.rb
# frozen_string_literal: true

# user model
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :stories, dependent: :destroy
  mount_uploader :image, ImageUploader
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, length: { maximum: 20 }, uniqueness: true
  validates :email, presence: true, format: Devise.email_regexp, uniqueness: true
  validate :password_complexity

  def password_complexity
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/

    errors.add :password,
               'Length should be 8-70 characters and include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# User controller
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: %i[edit update]

  def index
    @user_posts = current_user.posts
    @users = User.includes(:posts)
    redirect_to new_user_session_path unless user_signed_in?
  end

  def search
    @user_posts = current_user.posts
    @users = User.includes(:posts)
    @query = params[:query]
    @usersearch = User.find_by(username: @query)
    if current_user.username == @usersearch.username
      render 'index'
    else
      render 'search'
    end
  end

  def edit; end

  def update
    ActiveRecord::Base.transaction do
      if @user.update(user_params)
        redirect_to users_path
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  private

  def find_user
    @user = User.find_by id: params[:id]
    return if @user

    flash[:danger] = 'User does not exist!'
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/views/users/_gravatar.html.erb
<% if current_user.image.present? %>
    <%= link_to edit_user_registration_path(current_user) do %>
      <%= image_tag current_user.image.url, class: "rounded-circle mt-4", width: "50%", height: "90%" %>
    <% end %>
    <% else %>
    <%= link_to edit_user_registration_path(current_user) do %>
      <%= image_tag 'gravatar-pic', class: "rounded-circle mt-4", width: "50%", height: "90%" %>
      <% end %>
    <% end %>

app/views/users/index.html.erb
<div class="row">
    <div class="col-md-4 text-center mb-3">
     <%= render 'gravatar' %>
    </div>

    <div class="col-md-8">
        <div class="row mt-5">
            <h1 class="username col-5 mt-2"><%= current_user.username %></h1>
            <button class="btn btn-success col-2 mx-1"><%= link_to 'Edit User', edit_user_registration_path(current_user), class: "text-white" %></button>
                <button class="btn btn-success col-1 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fa-solid fa-gear"></button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <%= link_to 'Logout', destroy_user_session_path, class: "dropdown-item" %>
                </div>
        </div>
        <div class="row mt-3">
          <h3><%= current_user.email %></h3>
        </div>

        <div class="mt-3">
            <h5><%= current_user.bio %></h5>
        </div>
        <%= link_to 'Create Post', posts_path, class: "btn btn-success" %>
        <%= link_to 'Add to story', stories_path, class: "btn btn-success" %>
    </div>
    <hr>

    </div>
    <div class="row">
        <% @user_posts.each do |post| %>
    <div class = "card w-50">
        <div class = "card-header">
        <%= link_to users_path(post.user), title: post.user.username do %>
        <h4><%= post.user.username %></h4>
        <% end %>
        </div>
         <p class= "mx-2" ><%= post.content %></p>
         <%= link_to  posts_path do %>
        <div class="text-center mb-3">
        <%= image_tag post.photos.first.image.url, class: "rounded-circle", width: "30%" %>
        <% end %>
        </div>
    </div>
        <% end %>
    </div>
</div>
    <%= render 'shared/footer' if current_user %>

app/views/users/search.html.erb
<div class="row justify-content-md-center profile-wrapper">
    <div class="col-md-4 text-center">
    <% if @usersearch.image.present? %>
      <%= image_tag @usersearch.image.url, class: "rounded-circle mt-4", width: "50%", height: "90%" %>
    <% else %>
      <%= image_tag 'gravatar-pic', class: "rounded-circle mt-4", width: "50%", height: "90%" %>
    <% end %>
    </div>
    <div class="col-md-8">
        <div class="row mt-5">
            <h1 class="username col-5 mt-2"><%= @usersearch.username %></h1>
                <button class="btn btn-success col-2" type="button">Follow</button>
        </div>
        <div class="row mt-3">
            <h3 class="email"><%= @usersearch.email %></h3>
        </div>
    </div>
</div>