config/routes.rb
# frozen_string_literal: true

# routes
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources :users
  mount Sidekiq::Web => '/sidekiq'
  get '/search', to: 'users#search'
  resources :stories
  resources :posts do
    resources :photos, only: [:create]
    resources :likes, only: %i[create destroy], shallow: true
    resources :comments, shallow: true
  end
end

app/views/shared/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <span>
      <strong class =  "no-text-decoration normal-color">
        <%= comment.user.username%>
      </strong>
    </span>
    <span><%= comment.content %></span>
    <% if comment.user %>
      <%= button_to "Delete", comment_path(comment),
        method: :delete, remote: true %>
        <%= button_to edit_comment_path(comment) do %>
          <i class = "fas fa-edit" aria-hidden = "true"></i>
        <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_comment_not_found.html.erb
<div class= "card mt-5">
  <div class="card-header">
    <h1>Comment not found</h1>
  </div>
</div>
<%= link_to "Back", :back, class: "btn btn-success mt-5" %>

app/views/shared/_create_post.html.erb
<div class="d-flex flex-column align-items-center mt-3">
<div class="col-xl-7 col-lq-8 col-md-10 col-sm-11 post-card">
<div class="card">
<div class="card-header">
Create Post
</div>
<div class="card-body">
    <%= form_for @post, :html => {:multipart => true, :class => "p-0 border-0"} do |f| %>
    <div class="form-group row mt-2">
        <div class="col pl-0">
            <%= f.text_field :content, class: "form-control border-1", placeholder: "Insert caption", required: true %>
        </div>
        <div>
            <%= file_field_tag "images[]", type: :file, multiple: true , required: true, class: "mt-2" %>
             <%= f.submit "Post", class: "btn btn-success pull-right" %>
        </div>
    </div>
    <% end %>
            </div>
        </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer style= "
    margin-bottom:0px;">
  <nav class="navbar navbar-expand navbar-light bg-light">
      <div class="navbar-nav mx-auto">
        <a href="" class="nav-item nav-link" href="#">ABOUT US</a>
        <a href="" class="nav-item nav-link" href="#">SUPPORT</a>
        <a href="" class="nav-item nav-link" href="#">BLOG</a>
        <a href="" class="nav-item nav-link" href="#">PRESS</a>
        <a href="" class="nav-item nav-link" href="#">API</a>
        <a href="" class="nav-item nav-link" href="#">JOB</a>
        <a href="" class="nav-item nav-link" href="#">PRIVACY</a>
        <a href="" class="nav-item nav-link" href="#">TERMS</a>
        <a href="" class="nav-item nav-link" href="#">DIRECTORY</a>
        <a href="" class="nav-item nav-link" href="#">LANGUAGE</a>
      </div>
  </nav>
</footer>

app/views/shared/_navbar.html.erb
<div class="navigation">
  <div class="logo">
    <a class="no-underline">
  <%= link_to users_path(current_user) do %>
      Instagram-Clone
  <% end %>
    </a>
  </div>
  <div>
    <%= render 'shared/search' %>
  </div>

  <div class="navigation-icons">
      <%= link_to '---', users_path , class: "far fa-user-circle" %>
      <%= link_to '', destroy_user_session_path , class: "fas fa-sign-out-alt" %>
  </div>
</div>

app/views/shared/_post_body.html.erb
<div class="d-flex flex-column align-items-center mt-3">
    <div class = "col-xl-7 col-lq-8 col-md-10 col-sm-11 post-card">
        <div class="card">
            <div class="card-header">
                <% @posts.each do |post| %>
                <div class="card mt-3 post">
                    <div class = "card-header">
                        <%= link_to users_path(post.user), title: post.user.username do %>
                        <h4><%= post.user.username %></h4>
                          <%= button_to post_path(post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto pull-right" do %>
                            <i class = "far fa-trash-alt" aria-hidden = "true"></i>
                            <% end %>
                          <%= link_to edit_post_path(post) do %>
                             <i class = "fas fa-edit" aria-hidden = "true"></i>
                          <% end %>
                        <hr>
                        <% end %>
                     <% if post.photos.size == 1 %>
                      <%= image_tag post.photos.first.image.url(:standard), class: "card-img-top" %>
                    <% else %>
                      <div class="carousel slide" data-ride="carousel" id="carousel-post-<%= @post.id %>">
                        <div class="carousel-inner">
                          <% post.photos.each do |photo| %>
                            <% if photo == post.photos.first %>
                              <div class="carousel-item active">
                            <% else %>
                              <div class="carousel-item">
                            <% end %>
                                <%= image_tag photo.image.url(:standard), class: "card-img-top" %>
                              </div>
                          <% end %>
                        </div>
                        <a class="carousel-control-prev" href="#carousel-post-<%= @post.id %>" role="button" data-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carousel-post-<%= @post.id %>" role="button" data-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="sr-only">Next</span>
                        </a>
                      </div>
                    <% end %>
                      </div>
                    <div class="card-body">
                        <div class="actions" id="like-button-<%= @post.id.to_s %>">
                        <div>
                            <% @like = current_user.likes.find_by(post_id: post.id) %>
                            <% if @like.present? %>
                              <%= button_to image_tag("like_on.png", height: "30px"), like_path(id: @like.id), method: :delete, remote: true, class: "btn", style: "margin-left: -10px" %>
                            <% else %>
                              <%= button_to image_tag("like.png", height: "30px"), post_likes_path(post_id: post.id), method: :post, remote: true, class: " btn", style: "margin-left: -10px" %>
                          <% end %>
                          <span class= "mx-3"><%= post.likes.count %> likes</span>
                        </div>
                        <div class="mx-3">
                            <span><strong><%= post.user.username %></strong></span>
                            <span><%= post.content %></span>
                        </div>
                        <div class="light-color post-time mx-3 my-2"><%= time_ago_in_words(post.created_at) %> ago</div>
                        <div id="comment-form-post-<%= @post.id.to_s %>">
                          <%= render 'shared/comment_list', {post: post} %>
                        </div>
                        <div class="row actions mx-1" id="comment-form-post-<%= @post.id.to_s %>">
                            <%= form_for [post, Comment.new], :html => {:class => "w-100"}, remote: true do |f| %>
                                <%= f.hidden_field :user_id, value: current_user.id %>
                                <%= f.hidden_field :post_id, value: post.id %>
                                <%= f.text_field :content, class: "form-control comment-input border-1", placeholder: "Add a comment ...", autocomplete: :off %>
                                <% end %>
                        </div>
                    </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
    </div>
  </div>

app/views/shared/_search.html.erb
<form action="/search" method="get" accept-charset="UTF-8" >
  <input class="form-control" id="query" name="query" type="text" required=true placeholder="Search"/>
</form>

app/views/shared/_users_result.html.erb
<% if users.present? %>
    <% users.each do |user| %>
        <%= link_to user_path(user), class:"no-text-decoration normal-color" do %>
            <div class="search-result-item"><%= user.username %></div>
        <% end %>
    <% end %>
<% else %>
    <div class="p-3">
        no result found
    </div>
<% end %>