config/routes.rb
# frozen_string_literal: true

# routes
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources :users
  mount Sidekiq::Web => '/sidekiq'
  get '/search', to: 'users#search'
  resources :stories
  resources :posts do
    resources :photos, only: [:create]
    resources :likes, only: %i[create destroy], shallow: true
    resources :comments, shallow: true
  end
end

app/models/story.rb
# frozen_string_literal: true

# Story model
class Story < ApplicationRecord
  belongs_to :user
  has_many :photos, as: :imageable, dependent: :destroy
  validates :caption, presence: true
end

app/controllers/stories_controller.rb
# frozen_string_literal: true

# stories controller
class StoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_story, only: %i[show destroy]

  def index
    @stories = Story.all.limit(1000).includes(:photos, :user)
    @user_stories = current_user.stories
    @story = Story.new
  end

  def create
    @story = current_user.stories.create(story_params)
    image = params[:images]
    if @story.save
      image.each do |img|
        @story.photos.create(image: img)
      end
      flash[:notice] = 'Story Created'
    else
      flash[:alert] = 'Something went wrong!'
    end
    redirect_to stories_path
  end

  def show; end

  def destroy
    ActiveRecord::Base.transaction do
      if @story.destroy
        flash[:notice] = 'Story deleted'
      else
        flash[:alert] = 'Something went wrong ...'
      end
    end
    redirect_to stories_path
  end

  private

  def find_story
    @story = Story.find(params[:id])
    authorize @story
    return if @story

    flash[:danger] = 'Story does not exist'
    redirect_to root_path
  end

  def story_params
    params.require(:story).permit(:caption)
  end
end

app/views/stories/index.html.erb
<div class="d-flex flex-column align-items-center mt-3">
<div class="col-xl-7 col-lq-8 col-md-10 col-sm-11 post-card">
<div class="card">
<div class="card-header">
Create story
</div>
<div class="card-body">
        <%= form_for @story, :html => {:multipart => true, :class => "p-0 border-0"} do |f| %>
        <%= f.text_field :caption, class: "form-control", placeholder: "Insert caption", required: true %>
        <%= file_field_tag "images[]", type: :file, multiple: true , required: true %>
        <%= f.submit "Story", class: "btn btn-default btn-success mt-2 pull-right" %>
        <% end %>
            </div>
        </div>
    <br>
        <% @stories.each do |story| %>
    <div class="card w-50 mb-5">
        <div class="card-header text-center">
        <%= link_to users_path(story.user), title: story.user.username do %>
        <h4><%= story.user.username %></h4>
        <% end %>
        </div>
        <br>
        <p class= "mx-2" ><%= story.caption %></p>
            <%= button_to story_path(story), method: :delete, class: "ml-auto mx-0 my-auto pull-right" do %>
            <i class = "far fa-trash-alt" aria-hidden = "true"></i>
            <% end %>
        <% story.photos.each do |photo| %>
        <div class="text-center mb-3">
        <%= image_tag photo.image.url, class: "rounded-circle", width: "30%"%>
        </div>
        <% end %>
        </div>
        <% end %>
    </div>
</div>